// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu8MwlXkwgwHbLplpWqOiSVKN-WjoQroE',
    appId: '1:246253954238:web:e77cadc5961ccb2e222aef',
    messagingSenderId: '246253954238',
    projectId: 'edu-master-a0629',
    authDomain: 'edu-master-a0629.firebaseapp.com',
    storageBucket: 'edu-master-a0629.appspot.com',
    measurementId: 'G-MB14F1LCZJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSRZob3Q4lzyepbvFSp4cmWmeJUlOyl5U',
    appId: '1:246253954238:ios:bb3f7e921485702f222aef',
    messagingSenderId: '246253954238',
    projectId: 'edu-master-a0629',
    storageBucket: 'edu-master-a0629.appspot.com',
    iosBundleId: 'com.example.edumaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSRZob3Q4lzyepbvFSp4cmWmeJUlOyl5U',
    appId: '1:246253954238:ios:bb3f7e921485702f222aef',
    messagingSenderId: '246253954238',
    projectId: 'edu-master-a0629',
    storageBucket: 'edu-master-a0629.appspot.com',
    iosBundleId: 'com.example.edumaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu8MwlXkwgwHbLplpWqOiSVKN-WjoQroE',
    appId: '1:246253954238:web:2bd7b3a24a06faa7222aef',
    messagingSenderId: '246253954238',
    projectId: 'edu-master-a0629',
    authDomain: 'edu-master-a0629.firebaseapp.com',
    storageBucket: 'edu-master-a0629.appspot.com',
    measurementId: 'G-KJ2L8Z5WK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSXWbURV5Nd1eeoEWqbd4vhVH7FmrU7o',
    appId: '1:246253954238:android:19491108d4fef26a222aef',
    messagingSenderId: '246253954238',
    projectId: 'edu-master-a0629',
    storageBucket: 'edu-master-a0629.appspot.com',
  );

}